// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: proto/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SenderId  string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Payload   []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Type      int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // 0=team, 1=private, 2=file-browse-req, 3=file-browse-resp,
	// 4=file-meta-req, 5=file-meta-resp, 6=file-download-req,
	// 7=file-chunk, 8=peer-info-exchange, 9=heartbeat, 99=test
	ReceiverId    string `protobuf:"bytes,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // empty for team, target pubkey for private
	TeamId        string `protobuf:"bytes,6,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`             // team scope identifier, empty for default team
	ChannelId     string `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`    // empty for team-wide, channel ID for channel messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Envelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Envelope) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Envelope) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Envelope) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type MetadataSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Hlc           int64                  `protobuf:"varint,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataSyncRequest) Reset() {
	*x = MetadataSyncRequest{}
	mi := &file_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataSyncRequest) ProtoMessage() {}

func (x *MetadataSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataSyncRequest.ProtoReflect.Descriptor instead.
func (*MetadataSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataSyncRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MetadataSyncRequest) GetHlc() int64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

type MetadataSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Hlc           int64                  `protobuf:"varint,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataSyncResponse) Reset() {
	*x = MetadataSyncResponse{}
	mi := &file_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataSyncResponse) ProtoMessage() {}

func (x *MetadataSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataSyncResponse.ProtoReflect.Descriptor instead.
func (*MetadataSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataSyncResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MetadataSyncResponse) GetHlc() int64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *MetadataSyncResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TeamChallenge []byte                 `protobuf:"bytes,2,opt,name=team_challenge,json=teamChallenge,proto3" json:"team_challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HandshakeRequest) GetTeamChallenge() []byte {
	if x != nil {
		return x.TeamChallenge
	}
	return nil
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePubkey  string                 `protobuf:"bytes,1,opt,name=remote_pubkey,json=remotePubkey,proto3" json:"remote_pubkey,omitempty"`
	TeamMatch     bool                   `protobuf:"varint,2,opt,name=team_match,json=teamMatch,proto3" json:"team_match,omitempty"`
	TeamReply     []byte                 `protobuf:"bytes,3,opt,name=team_reply,json=teamReply,proto3" json:"team_reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *HandshakeResponse) GetRemotePubkey() string {
	if x != nil {
		return x.RemotePubkey
	}
	return ""
}

func (x *HandshakeResponse) GetTeamMatch() bool {
	if x != nil {
		return x.TeamMatch
	}
	return false
}

func (x *HandshakeResponse) GetTeamReply() []byte {
	if x != nil {
		return x.TeamReply
	}
	return nil
}

var File_proto_chat_proto protoreflect.FileDescriptor

const file_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x10proto/chat.proto\x12\x0eparade.chat.v1\"\xcc\x01\n" +
	"\bEnvelope\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1f\n" +
	"\vreceiver_id\x18\x05 \x01(\tR\n" +
	"receiverId\x12\x17\n" +
	"\ateam_id\x18\x06 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\a \x01(\tR\tchannelId\"D\n" +
	"\x13MetadataSyncRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03hlc\x18\x02 \x01(\x03R\x03hlc\"_\n" +
	"\x14MetadataSyncResponse\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03hlc\x18\x02 \x01(\x03R\x03hlc\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"V\n" +
	"\x10HandshakeRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12%\n" +
	"\x0eteam_challenge\x18\x02 \x01(\fR\rteamChallenge\"v\n" +
	"\x11HandshakeResponse\x12#\n" +
	"\rremote_pubkey\x18\x01 \x01(\tR\fremotePubkey\x12\x1d\n" +
	"\n" +
	"team_match\x18\x02 \x01(\bR\tteamMatch\x12\x1d\n" +
	"\n" +
	"team_reply\x18\x03 \x01(\fR\tteamReply2\x84\x02\n" +
	"\vChatService\x12D\n" +
	"\n" +
	"StreamChat\x12\x18.parade.chat.v1.Envelope\x1a\x18.parade.chat.v1.Envelope(\x010\x01\x12]\n" +
	"\fSyncMetadata\x12#.parade.chat.v1.MetadataSyncRequest\x1a$.parade.chat.v1.MetadataSyncResponse(\x010\x01\x12P\n" +
	"\tHandshake\x12 .parade.chat.v1.HandshakeRequest\x1a!.parade.chat.v1.HandshakeResponseB*Z(parade/internal/network/pb/chatpb;chatpbb\x06proto3"

var (
	file_proto_chat_proto_rawDescOnce sync.Once
	file_proto_chat_proto_rawDescData []byte
)

func file_proto_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)))
	})
	return file_proto_chat_proto_rawDescData
}

var file_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_chat_proto_goTypes = []any{
	(*Envelope)(nil),             // 0: parade.chat.v1.Envelope
	(*MetadataSyncRequest)(nil),  // 1: parade.chat.v1.MetadataSyncRequest
	(*MetadataSyncResponse)(nil), // 2: parade.chat.v1.MetadataSyncResponse
	(*HandshakeRequest)(nil),     // 3: parade.chat.v1.HandshakeRequest
	(*HandshakeResponse)(nil),    // 4: parade.chat.v1.HandshakeResponse
}
var file_proto_chat_proto_depIdxs = []int32{
	0, // 0: parade.chat.v1.ChatService.StreamChat:input_type -> parade.chat.v1.Envelope
	1, // 1: parade.chat.v1.ChatService.SyncMetadata:input_type -> parade.chat.v1.MetadataSyncRequest
	3, // 2: parade.chat.v1.ChatService.Handshake:input_type -> parade.chat.v1.HandshakeRequest
	0, // 3: parade.chat.v1.ChatService.StreamChat:output_type -> parade.chat.v1.Envelope
	2, // 4: parade.chat.v1.ChatService.SyncMetadata:output_type -> parade.chat.v1.MetadataSyncResponse
	4, // 5: parade.chat.v1.ChatService.Handshake:output_type -> parade.chat.v1.HandshakeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chat_proto_init() }
func file_proto_chat_proto_init() {
	if File_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_proto = out.File
	file_proto_chat_proto_goTypes = nil
	file_proto_chat_proto_depIdxs = nil
}
