// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectoryToShareGroup(arg1, arg2) {
  return window['go']['app']['App']['AddDirectoryToShareGroup'](arg1, arg2);
}

export function CheckHasIdentity() {
  return window['go']['app']['App']['CheckHasIdentity']();
}

export function ConnectToPeer(arg1) {
  return window['go']['app']['App']['ConnectToPeer'](arg1);
}

export function CreateShareGroup(arg1) {
  return window['go']['app']['App']['CreateShareGroup'](arg1);
}

export function DeleteShareGroup(arg1) {
  return window['go']['app']['App']['DeleteShareGroup'](arg1);
}

export function ExportLogs() {
  return window['go']['app']['App']['ExportLogs']();
}

export function GetActiveTeam() {
  return window['go']['app']['App']['GetActiveTeam']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetConversationMessages(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetConversationMessages'](arg1, arg2, arg3);
}

export function GetDefaultDownloadDir() {
  return window['go']['app']['App']['GetDefaultDownloadDir']();
}

export function GetDirectoryChildren(arg1) {
  return window['go']['app']['App']['GetDirectoryChildren'](arg1);
}

export function GetPeers() {
  return window['go']['app']['App']['GetPeers']();
}

export function GetPeersWithStatus() {
  return window['go']['app']['App']['GetPeersWithStatus']();
}

export function GetPubKey() {
  return window['go']['app']['App']['GetPubKey']();
}

export function GetRemoteDirectoryChildren(arg1, arg2) {
  return window['go']['app']['App']['GetRemoteDirectoryChildren'](arg1, arg2);
}

export function GetShareGroupDirs(arg1) {
  return window['go']['app']['App']['GetShareGroupDirs'](arg1);
}

export function JoinTeam(arg1) {
  return window['go']['app']['App']['JoinTeam'](arg1);
}

export function JoinTeamWithName(arg1, arg2) {
  return window['go']['app']['App']['JoinTeamWithName'](arg1, arg2);
}

export function LeaveTeam(arg1) {
  return window['go']['app']['App']['LeaveTeam'](arg1);
}

export function ListConversations() {
  return window['go']['app']['App']['ListConversations']();
}

export function ListShareGroups() {
  return window['go']['app']['App']['ListShareGroups']();
}

export function ListTeams() {
  return window['go']['app']['App']['ListTeams']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function OnForeground() {
  return window['go']['app']['App']['OnForeground']();
}

export function Register(arg1) {
  return window['go']['app']['App']['Register'](arg1);
}

export function RemoveDirectoryFromShareGroup(arg1, arg2) {
  return window['go']['app']['App']['RemoveDirectoryFromShareGroup'](arg1, arg2);
}

export function SendPrivateChat(arg1, arg2) {
  return window['go']['app']['App']['SendPrivateChat'](arg1, arg2);
}

export function SendTeamChat(arg1) {
  return window['go']['app']['App']['SendTeamChat'](arg1);
}

export function ShareDirectory(arg1) {
  return window['go']['app']['App']['ShareDirectory'](arg1);
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartDownload'](arg1, arg2, arg3);
}

export function StartPrivateConversation(arg1) {
  return window['go']['app']['App']['StartPrivateConversation'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function SwitchTeam(arg1) {
  return window['go']['app']['App']['SwitchTeam'](arg1);
}

export function UnshareDirectory(arg1) {
  return window['go']['app']['App']['UnshareDirectory'](arg1);
}

export function WriteLogFile(arg1, arg2) {
  return window['go']['app']['App']['WriteLogFile'](arg1, arg2);
}
