// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddDirectoryToShareGroup(arg1:string,arg2:string):Promise<void>;

export function CheckHasIdentity():Promise<boolean>;

export function ConnectToPeer(arg1:string):Promise<Record<string, any>>;

export function CreateShareGroup(arg1:string):Promise<string>;

export function DeleteShareGroup(arg1:string):Promise<void>;

export function ExportLogs():Promise<Record<string, any>>;

export function GetActiveTeam():Promise<string>;

export function GetContext():Promise<context.Context>;

export function GetConversationMessages(arg1:string,arg2:number,arg3:number):Promise<Array<Record<string, any>>>;

export function GetDefaultDownloadDir():Promise<string>;

export function GetDirectoryChildren(arg1:string):Promise<any>;

export function GetPeers():Promise<Array<Record<string, string>>>;

export function GetPeersWithStatus():Promise<Array<Record<string, any>>>;

export function GetPubKey():Promise<string>;

export function GetRemoteDirectoryChildren(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetShareGroupDirs(arg1:string):Promise<Array<Record<string, any>>>;

export function JoinTeam(arg1:string):Promise<void>;

export function JoinTeamWithName(arg1:string,arg2:string):Promise<string>;

export function LeaveTeam(arg1:string):Promise<void>;

export function ListConversations():Promise<Array<Record<string, any>>>;

export function ListShareGroups():Promise<Array<Record<string, any>>>;

export function ListTeams():Promise<Array<Record<string, any>>>;

export function Login(arg1:string):Promise<void>;

export function OnForeground():Promise<void>;

export function Register(arg1:string):Promise<void>;

export function RemoveDirectoryFromShareGroup(arg1:string,arg2:string):Promise<void>;

export function SendPrivateChat(arg1:string,arg2:string):Promise<void>;

export function SendTeamChat(arg1:string):Promise<void>;

export function ShareDirectory(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartPrivateConversation(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function SwitchTeam(arg1:string):Promise<void>;

export function UnshareDirectory(arg1:string):Promise<void>;

export function WriteLogFile(arg1:string,arg2:string):Promise<void>;
